---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: update repo cache (Amazon)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"



- hosts: all
  become: true
  tasks:
  
  - name: add ssh key for taiwo
    tags: key
    authorized_key:
      user: taiwo
      key: "publickeycontent"



- hosts: workstations
  become: true
  tasks:
 
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root



- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package for Amazon servers
    tags: apache,amazon,httpd
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: start httpd (Amazon)
    tags: apache,amazon,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Amazon"


  - name: install apache and php package for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2                 
        - libapache2-mod-php            
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: change e-mail address for admin
    tags: apache,apache2,httpd,change
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin example@somewhere.net
    when: ansible_distribution == "Amazon"
    register: config

  - name: restart httpd (Amazon)
    tags: apache,httpd,restart
    service:
      name: httpd
      state: restarted
    when: config.changed 


  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

   
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Amazon)
    tags: amazon,db,mariadb
    yum:
      name: mariadb105-server
      state: latest
    when: ansible_distribution == "Amazon"
  
  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba 
    package:
      name: samba
      state: latest
